#===========================================================================
# allowed DPIs
#===========================================================================
dpis: [254, 190, 127]

#===========================================================================
# allowed Formats
#===========================================================================
formats: ['*']

#===========================================================================
# the allowed scales
#===========================================================================
scales:
  - 250
  - 500
  - 1000
  - 2500
  - 5000
  - 10000
  - 20000

#===========================================================================
# the list of allowed hosts
#===========================================================================
hosts:
  - !localMatch
    dummy: true
  - !ipMatch
    ip: www.camptocamp.org
  - !dnsMatch
    host: labs.metacarta.com
    port: 80
  - !dnsMatch
    host: terraservice.net
    port: 80
  - !dnsMatch
    host: tile.openstreetmap.org
    port: 80
  - !ipMatch
    ip: 89.16.179.114
    port: 8008
  - !dnsMatch
    host: cartopro1.wallonie.be
    port: 80
  - !dnsMatch
    host: cartocit2.wallonie.be
    port: 80
  - !dnsMatch
    host: geoservices.wallonie.be
    port: 80
  - !dnsMatch
    host: geonode.imio.be
    port: 443
  - !dnsMatch
    host: webgisdgo4.spw.wallonie.be
    port: 80
    
layouts:
  #===========================================================================
  A4 portrait:
  #===========================================================================
    metaData:
      title: '${title}'
      author: 'UrbanMap print module'
      subject: 'Simple layout'
      keywords: 'map,print,geode,urbanmap'
      creator: 'Geode SPRL'

    titlePage:
      pageSize: A4
      items:
        - !text
          spacingAfter: 150
        - !text
          font: Helvetica
          fontSize: 40
          spacingAfter: 20
          align: center
          text: '${title}'
        - !text
          font: Helvetica
          fontSize: 20
          spacingAfter: 100
          align: center
          text: 'Caneva de document'
        - !image
          maxWidth: 500
          maxHeight: 400
          spacingAfter: 100
          align: center
          url: http://localhost:5000/app/img/arrondissements.jpg
        - !text
          font: Arial
          fontSize: 15
          spacingAfter: 15
          align: center
          text: 'Commune Plone'
        - !text
          font: Helvetica
          fontSize: 14
          align: left
          text: |
            Template de génération de document pour l'application UrbanMap:
            - Ce template peut être modifié sur demande

      footer: &commonFooter
        height: 30
        items:
          - !columns
            config:
              cells:
                - paddingBottom: 5
            items:
              - !text
                backgroundColor: #FFFFFF
                align: left
                text: ©Geode SPRL
              - !text
                align: right
                text: 'Page ${pageNum}'

    #-------------------------------------------------------------------------
    mainPage:
      pageSize: A4
      rotation: true
      header:
        height: 50
        items:
          - !text
            font: Arial
            fontSize: 30
            align: left
            text: '${mapTitle}'
      items:
        - !map
          spacingAfter: 30
          width: 440
          height: 483
        - !columns
          # columns can have an absolute position. In that case, they need the 3 following fields:
          absoluteX: 410
          absoluteY: 310
          width: 100
          items:
            - !scalebar
              type: bar
              maxSize: 100
              barBgColor: white
              fontSize: 8
              align: right
        - !text
          text: '${comment}'
          spacingAfter: 30
        - !attributes
          source: data
          spacingAfter: 30
          columnDefs:
            id:
              columnWeight: 2
              header: !text
                text: ID
                backgroundColor: #A0A0A0
              cell: !text
                text: '${id}'
            name:
              columnWeight: 5
              header: !text
                text: Name
                backgroundColor: #A0A0A0
              cell: !columns
                config:
                  cells:
                    - backgroundColor: '${nameBackgroundColor}'
                      borderWidth: 1
                      borderColor: '${nameBorderColor}'
                items:
                  - !text
                    text: '${name}'
            icon:
              columnWeight: 2
              header: !text
                text: Symbol
                backgroundColor: #A0A0A0
              cell: !image
                align: center
                maxWidth: 15
                maxHeight: 15
                url: 'http://www.mapfish.org/svn/mapfish/framework/client/trunk/mfbase/mapfish/img/${icon}.png'
        - !text
          font: Helvetica
          fontSize: 9
          align: right
          text: '1:${scale} ${now MM.dd.yyyy}'
      footer: *commonFooter
